### PR TITLE
Force blur update to also catch if alpha channel is 255

### PR DESCRIPTION
**Pull request by DeltaCopy**
To avoid the translucent background when showing/hiding the Menubar in Dolphin

### CODE REVIEW

**Comment by DeltaCopy** [comment]
The initial fix for #82 caused a regression, whereby the menubar was flickering upon hiding/showing.
Removed register blur from drawing the toolbar background, and ensured  that if the alpha channel is 255 then force blur inside the event filter where it should be repainted.

**Comment by subhasutra** [comment]
This fixes the flickering for me. 👍🏼

**Comment by DeltaCopy** [comment]
Thank you for testing again @subhasutra.

I have merged up into the feature branch.

**Comment by Bali10050** [comment]
Thank you @DeltaCopy for the fix!

**Pull request merged**
